### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by orbisvicis** [tukkek/javelin#234]
```$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

```java -jar javelin.jar
Exception in thread "Thread-151" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
	at javelin.controller.generator.feature.FeatureGenerator.generateuniquelocations(FeatureGenerator.java:183)
	at javelin.controller.generator.feature.FeatureGenerator.generatestartinglocations(FeatureGenerator.java:175)
	at javelin.controller.generator.feature.FeatureGenerator.generatefeatures(FeatureGenerator.java:248)
	at javelin.controller.generator.feature.FeatureGenerator.generate(FeatureGenerator.java:237)
	at javelin.controller.generator.WorldGenerator.generate(WorldGenerator.java:64)
	at javelin.controller.generator.WorldGenerator.run(WorldGenerator.java:42)
Exception in thread "Thread-197" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
	at javelin.controller.generator.feature.FeatureGenerator.generateuniquelocations(FeatureGenerator.java:183)
	at javelin.controller.generator.feature.FeatureGenerator.generatestartinglocations(FeatureGenerator.java:175)
	at javelin.controller.generator.feature.FeatureGenerator.generatefeatures(FeatureGenerator.java:248)
	at javelin.controller.generator.feature.FeatureGenerator.generate(FeatureGenerator.java:237)
	at javelin.controller.generator.WorldGenerator.generate(WorldGenerator.java:64)
	at javelin.controller.generator.WorldGenerator.run(WorldGenerator.java:42)
```

I'm on Fedora and probably missing a package... but I can't find `List.of()` in the [List (Java Platform SE 8)](https://docs.oracle.com/javase/8/docs/api/java/util/List.html) documentation either.

[FeatureGenerator.java#L184](https://github.com/tukkek/javelin/blob/1.7/javelin/controller/generator/feature/FeatureGenerator.java#L184)

**Comment by orbisvicis** [comment]
Oh, [Java SE 9](https://docs.oracle.com/javase/9/docs/api/java/util/List.html)+

*Edit: and it works with openjdk-11.0.1*

**Comment by orbisvicis** [comment]
On openjdk 11, immediately after generation:

```
You were eaten by a grue.

Unfortunately an error ocurred.
Please send a screenshot of the next message or the log file (error.txt)
to one of the channels below, so we can get this fixed on future releases.

If for any reason your current game fails to load when you restart Javelin
you can find backups on the "backup" folder. Just move one of them to the
main folder and rename it to "javelin.save" to restore your progress.
```

Can't find `error.txt`.
